services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: omnisend-redis
    ports:
      - "6379:6379"
    networks:
      - omnisend-network
    restart: always

  notification-db:
    image: postgres:16
    container_name: omnisend-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    ports:
      - "5434:5432"
    networks:
      - omnisend-network
    restart: always

networks:
  omnisend-network:
    driver: bridge